In [67]:
import numpy as np
import pandas as pd

#Import Train and Test dataset
train_df = pd.read_csv("balanced_train_set.csv")
test_df = pd.read_csv("balanced_test_set.csv")

#Select Feature and Target
X = train_df[["states", "actions", "uncertainty", "sparse", "tot_tests", "prior", "score"]]
y = train_df[["best_strategy"]]
X_test = test_df[["states", "actions", "uncertainty", "sparse", "tot_tests", "prior", "score"]]
y_test = test_df[["best_strategy"]]

#[Testing] print Train and Test dataset
#print(train_df)
#print(test_df)


In [68]:
#Training data with a multinomial logistic regression model

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

m1 = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=10000).fit(X,y.values.ravel())
y_pred = m1.predict(X_test)
cm1 = confusion_matrix(y_test, y_pred, labels=["hist","flat","dist","freq"])
print(cm1)
print("Accuracy score: ", m1.score(X_test, y_test))

[[8 0 1 0]
 [2 7 0 0]
 [1 3 3 2]
 [1 6 0 3]]
Accuracy score:  0.5675675675675675


In [69]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred))

0.5675675675675675
