In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

In [26]:
#df = pd.read_csv("balanced_dataset.csv")
df = pd.read_csv("dataset0.csv")
#df = pd.read_csv("subset_data.csv")

In [27]:
from sklearn.model_selection import train_test_split

# encode "bal" with 1, "unbal" with 0
for index, row in df.iterrows():
	if row["prior"] == "bal":
		df.loc[index,"prior"]=1
	elif row["prior"] == "unbal":
		df.loc[index,"prior"]=0



X = df[["states", "actions", "uncertainty", "sparse", "tot_tests", "prior"]]
#y = df[["dist","flat","freq","hist"]]
y = df[["best_strategy"]]
#y = pd.get_dummies(df['best_strategy'])


#Split train and test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, stratify= y)


In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=100)
print(y)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)
cm1 = confusion_matrix(y_test, y_pred, labels=["hist","flat","dist","freq"])
print(cm1)
print("Accuracy score: ", model.score(X_test, y_test))

    best_strategy
0            dist
1            dist
2            dist
3            dist
4            dist
..            ...
990          flat
991          freq
992          dist
993          dist
994          freq

[995 rows x 1 columns]
[[ 0  1  4  0]
 [ 0 12 12  6]
 [ 0 12 83  8]
 [ 0 11 46  4]]
Accuracy score:  0.49748743718592964


/Users/ahmedharrabi/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ahmedharrabi/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
